/**
 * @fileoverview gRPC-Web generated client stub for 
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v3.15.6
// source: scratchservice.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var observor_pb = require('./observor_pb.js')

var apimessage_pb = require('./apimessage_pb.js')
const proto = require('./scratchservice_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ScratchServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.ScratchServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.RestoreCameraRequest,
 *   !proto.RestoreCameraResponse>}
 */
const methodDescriptor_ScratchService_restoreCamera = new grpc.web.MethodDescriptor(
  '/ScratchService/restoreCamera',
  grpc.web.MethodType.UNARY,
  apimessage_pb.RestoreCameraRequest,
  apimessage_pb.RestoreCameraResponse,
  /**
   * @param {!proto.RestoreCameraRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.RestoreCameraResponse.deserializeBinary
);


/**
 * @param {!proto.RestoreCameraRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.RestoreCameraResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.RestoreCameraResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.restoreCamera =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/restoreCamera',
      request,
      metadata || {},
      methodDescriptor_ScratchService_restoreCamera,
      callback);
};


/**
 * @param {!proto.RestoreCameraRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.RestoreCameraResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.restoreCamera =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/restoreCamera',
      request,
      metadata || {},
      methodDescriptor_ScratchService_restoreCamera);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetCameraFocussedVesselRequest,
 *   !proto.SetCameraFocussedVesselResponse>}
 */
const methodDescriptor_ScratchService_setCameraFocussedVessel = new grpc.web.MethodDescriptor(
  '/ScratchService/setCameraFocussedVessel',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetCameraFocussedVesselRequest,
  apimessage_pb.SetCameraFocussedVesselResponse,
  /**
   * @param {!proto.SetCameraFocussedVesselRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetCameraFocussedVesselResponse.deserializeBinary
);


/**
 * @param {!proto.SetCameraFocussedVesselRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetCameraFocussedVesselResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetCameraFocussedVesselResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setCameraFocussedVessel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setCameraFocussedVessel',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setCameraFocussedVessel,
      callback);
};


/**
 * @param {!proto.SetCameraFocussedVesselRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetCameraFocussedVesselResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setCameraFocussedVessel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setCameraFocussedVessel',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setCameraFocussedVessel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetCameraModeRequest,
 *   !proto.SetCameraModeResponse>}
 */
const methodDescriptor_ScratchService_setCameraMode = new grpc.web.MethodDescriptor(
  '/ScratchService/setCameraMode',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetCameraModeRequest,
  apimessage_pb.SetCameraModeResponse,
  /**
   * @param {!proto.SetCameraModeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetCameraModeResponse.deserializeBinary
);


/**
 * @param {!proto.SetCameraModeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetCameraModeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetCameraModeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setCameraMode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setCameraMode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setCameraMode,
      callback);
};


/**
 * @param {!proto.SetCameraModeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetCameraModeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setCameraMode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setCameraMode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setCameraMode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetManeuverNodeRequest,
 *   !proto.SetManeuverNodeResponse>}
 */
const methodDescriptor_ScratchService_setManeuverNode = new grpc.web.MethodDescriptor(
  '/ScratchService/setManeuverNode',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetManeuverNodeRequest,
  apimessage_pb.SetManeuverNodeResponse,
  /**
   * @param {!proto.SetManeuverNodeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetManeuverNodeResponse.deserializeBinary
);


/**
 * @param {!proto.SetManeuverNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetManeuverNodeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetManeuverNodeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setManeuverNode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setManeuverNode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setManeuverNode,
      callback);
};


/**
 * @param {!proto.SetManeuverNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetManeuverNodeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setManeuverNode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setManeuverNode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setManeuverNode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetManeuverNodeRequest,
 *   !proto.GetManeuverNodeResponse>}
 */
const methodDescriptor_ScratchService_getManeuverNode = new grpc.web.MethodDescriptor(
  '/ScratchService/getManeuverNode',
  grpc.web.MethodType.UNARY,
  apimessage_pb.GetManeuverNodeRequest,
  apimessage_pb.GetManeuverNodeResponse,
  /**
   * @param {!proto.GetManeuverNodeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.GetManeuverNodeResponse.deserializeBinary
);


/**
 * @param {!proto.GetManeuverNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetManeuverNodeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetManeuverNodeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.getManeuverNode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/getManeuverNode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getManeuverNode,
      callback);
};


/**
 * @param {!proto.GetManeuverNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetManeuverNodeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.getManeuverNode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/getManeuverNode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getManeuverNode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ListManeuverNodesRequest,
 *   !proto.ListManeuverNodesResponse>}
 */
const methodDescriptor_ScratchService_listManeuverNodes = new grpc.web.MethodDescriptor(
  '/ScratchService/listManeuverNodes',
  grpc.web.MethodType.UNARY,
  apimessage_pb.ListManeuverNodesRequest,
  apimessage_pb.ListManeuverNodesResponse,
  /**
   * @param {!proto.ListManeuverNodesRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.ListManeuverNodesResponse.deserializeBinary
);


/**
 * @param {!proto.ListManeuverNodesRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ListManeuverNodesResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ListManeuverNodesResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.listManeuverNodes =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/listManeuverNodes',
      request,
      metadata || {},
      methodDescriptor_ScratchService_listManeuverNodes,
      callback);
};


/**
 * @param {!proto.ListManeuverNodesRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ListManeuverNodesResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.listManeuverNodes =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/listManeuverNodes',
      request,
      metadata || {},
      methodDescriptor_ScratchService_listManeuverNodes);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.RemoveManeuverNodeRequest,
 *   !proto.RemoveManeuverNodeResponse>}
 */
const methodDescriptor_ScratchService_removeManeuverNode = new grpc.web.MethodDescriptor(
  '/ScratchService/removeManeuverNode',
  grpc.web.MethodType.UNARY,
  apimessage_pb.RemoveManeuverNodeRequest,
  apimessage_pb.RemoveManeuverNodeResponse,
  /**
   * @param {!proto.RemoveManeuverNodeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.RemoveManeuverNodeResponse.deserializeBinary
);


/**
 * @param {!proto.RemoveManeuverNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.RemoveManeuverNodeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.RemoveManeuverNodeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.removeManeuverNode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/removeManeuverNode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_removeManeuverNode,
      callback);
};


/**
 * @param {!proto.RemoveManeuverNodeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.RemoveManeuverNodeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.removeManeuverNode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/removeManeuverNode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_removeManeuverNode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.UniversalTimeRequest,
 *   !proto.UniversalTimeResponse>}
 */
const methodDescriptor_ScratchService_universalTime = new grpc.web.MethodDescriptor(
  '/ScratchService/universalTime',
  grpc.web.MethodType.UNARY,
  apimessage_pb.UniversalTimeRequest,
  apimessage_pb.UniversalTimeResponse,
  /**
   * @param {!proto.UniversalTimeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.UniversalTimeResponse.deserializeBinary
);


/**
 * @param {!proto.UniversalTimeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.UniversalTimeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.UniversalTimeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.universalTime =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/universalTime',
      request,
      metadata || {},
      methodDescriptor_ScratchService_universalTime,
      callback);
};


/**
 * @param {!proto.UniversalTimeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.UniversalTimeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.universalTime =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/universalTime',
      request,
      metadata || {},
      methodDescriptor_ScratchService_universalTime);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.WarpToRequest,
 *   !proto.WarpToResponse>}
 */
const methodDescriptor_ScratchService_warpTo = new grpc.web.MethodDescriptor(
  '/ScratchService/warpTo',
  grpc.web.MethodType.UNARY,
  apimessage_pb.WarpToRequest,
  apimessage_pb.WarpToResponse,
  /**
   * @param {!proto.WarpToRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.WarpToResponse.deserializeBinary
);


/**
 * @param {!proto.WarpToRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.WarpToResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.WarpToResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.warpTo =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/warpTo',
      request,
      metadata || {},
      methodDescriptor_ScratchService_warpTo,
      callback);
};


/**
 * @param {!proto.WarpToRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.WarpToResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.warpTo =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/warpTo',
      request,
      metadata || {},
      methodDescriptor_ScratchService_warpTo);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.WarpToSecondsAfterRequest,
 *   !proto.WarpToSecondsAfterRequest>}
 */
const methodDescriptor_ScratchService_warpToSecondsAfter = new grpc.web.MethodDescriptor(
  '/ScratchService/warpToSecondsAfter',
  grpc.web.MethodType.UNARY,
  apimessage_pb.WarpToSecondsAfterRequest,
  apimessage_pb.WarpToSecondsAfterRequest,
  /**
   * @param {!proto.WarpToSecondsAfterRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.WarpToSecondsAfterRequest.deserializeBinary
);


/**
 * @param {!proto.WarpToSecondsAfterRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.WarpToSecondsAfterRequest)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.WarpToSecondsAfterRequest>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.warpToSecondsAfter =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/warpToSecondsAfter',
      request,
      metadata || {},
      methodDescriptor_ScratchService_warpToSecondsAfter,
      callback);
};


/**
 * @param {!proto.WarpToSecondsAfterRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.WarpToSecondsAfterRequest>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.warpToSecondsAfter =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/warpToSecondsAfter',
      request,
      metadata || {},
      methodDescriptor_ScratchService_warpToSecondsAfter);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.IncreaseTimeWarpRateRequest,
 *   !proto.IncreaseTimeWarpRateResponse>}
 */
const methodDescriptor_ScratchService_increaseTimeWarpRate = new grpc.web.MethodDescriptor(
  '/ScratchService/increaseTimeWarpRate',
  grpc.web.MethodType.UNARY,
  apimessage_pb.IncreaseTimeWarpRateRequest,
  apimessage_pb.IncreaseTimeWarpRateResponse,
  /**
   * @param {!proto.IncreaseTimeWarpRateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.IncreaseTimeWarpRateResponse.deserializeBinary
);


/**
 * @param {!proto.IncreaseTimeWarpRateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.IncreaseTimeWarpRateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.IncreaseTimeWarpRateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.increaseTimeWarpRate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/increaseTimeWarpRate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_increaseTimeWarpRate,
      callback);
};


/**
 * @param {!proto.IncreaseTimeWarpRateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.IncreaseTimeWarpRateResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.increaseTimeWarpRate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/increaseTimeWarpRate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_increaseTimeWarpRate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DecreaseTimeWarpRateRequest,
 *   !proto.DecreaseTimeWarpRateResponse>}
 */
const methodDescriptor_ScratchService_decreaseTimeWarpRate = new grpc.web.MethodDescriptor(
  '/ScratchService/decreaseTimeWarpRate',
  grpc.web.MethodType.UNARY,
  apimessage_pb.DecreaseTimeWarpRateRequest,
  apimessage_pb.DecreaseTimeWarpRateResponse,
  /**
   * @param {!proto.DecreaseTimeWarpRateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.DecreaseTimeWarpRateResponse.deserializeBinary
);


/**
 * @param {!proto.DecreaseTimeWarpRateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DecreaseTimeWarpRateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DecreaseTimeWarpRateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.decreaseTimeWarpRate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/decreaseTimeWarpRate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_decreaseTimeWarpRate,
      callback);
};


/**
 * @param {!proto.DecreaseTimeWarpRateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DecreaseTimeWarpRateResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.decreaseTimeWarpRate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/decreaseTimeWarpRate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_decreaseTimeWarpRate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.IncreaseTimeWarpRateByRequest,
 *   !proto.IncreaseTimeWarpRateByResponse>}
 */
const methodDescriptor_ScratchService_increaseTimeWarpRateBy = new grpc.web.MethodDescriptor(
  '/ScratchService/increaseTimeWarpRateBy',
  grpc.web.MethodType.UNARY,
  apimessage_pb.IncreaseTimeWarpRateByRequest,
  apimessage_pb.IncreaseTimeWarpRateByResponse,
  /**
   * @param {!proto.IncreaseTimeWarpRateByRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.IncreaseTimeWarpRateByResponse.deserializeBinary
);


/**
 * @param {!proto.IncreaseTimeWarpRateByRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.IncreaseTimeWarpRateByResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.IncreaseTimeWarpRateByResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.increaseTimeWarpRateBy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/increaseTimeWarpRateBy',
      request,
      metadata || {},
      methodDescriptor_ScratchService_increaseTimeWarpRateBy,
      callback);
};


/**
 * @param {!proto.IncreaseTimeWarpRateByRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.IncreaseTimeWarpRateByResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.increaseTimeWarpRateBy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/increaseTimeWarpRateBy',
      request,
      metadata || {},
      methodDescriptor_ScratchService_increaseTimeWarpRateBy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DecreaseTimeWarpRateByRequest,
 *   !proto.DecreaseTimeWarpRateByResponse>}
 */
const methodDescriptor_ScratchService_decreaseTimeWarpRateBy = new grpc.web.MethodDescriptor(
  '/ScratchService/decreaseTimeWarpRateBy',
  grpc.web.MethodType.UNARY,
  apimessage_pb.DecreaseTimeWarpRateByRequest,
  apimessage_pb.DecreaseTimeWarpRateByResponse,
  /**
   * @param {!proto.DecreaseTimeWarpRateByRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.DecreaseTimeWarpRateByResponse.deserializeBinary
);


/**
 * @param {!proto.DecreaseTimeWarpRateByRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DecreaseTimeWarpRateByResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DecreaseTimeWarpRateByResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.decreaseTimeWarpRateBy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/decreaseTimeWarpRateBy',
      request,
      metadata || {},
      methodDescriptor_ScratchService_decreaseTimeWarpRateBy,
      callback);
};


/**
 * @param {!proto.DecreaseTimeWarpRateByRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DecreaseTimeWarpRateByResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.decreaseTimeWarpRateBy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/decreaseTimeWarpRateBy',
      request,
      metadata || {},
      methodDescriptor_ScratchService_decreaseTimeWarpRateBy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.StopTimeWarpRequest,
 *   !proto.StopTimeWarpResponse>}
 */
const methodDescriptor_ScratchService_stopTimeWarp = new grpc.web.MethodDescriptor(
  '/ScratchService/stopTimeWarp',
  grpc.web.MethodType.UNARY,
  apimessage_pb.StopTimeWarpRequest,
  apimessage_pb.StopTimeWarpResponse,
  /**
   * @param {!proto.StopTimeWarpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.StopTimeWarpResponse.deserializeBinary
);


/**
 * @param {!proto.StopTimeWarpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.StopTimeWarpResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.StopTimeWarpResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.stopTimeWarp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/stopTimeWarp',
      request,
      metadata || {},
      methodDescriptor_ScratchService_stopTimeWarp,
      callback);
};


/**
 * @param {!proto.StopTimeWarpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.StopTimeWarpResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.stopTimeWarp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/stopTimeWarp',
      request,
      metadata || {},
      methodDescriptor_ScratchService_stopTimeWarp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetTimeWarpRateRequest,
 *   !proto.GetTimeWarpRateResponse>}
 */
const methodDescriptor_ScratchService_getTimeWarpRate = new grpc.web.MethodDescriptor(
  '/ScratchService/getTimeWarpRate',
  grpc.web.MethodType.UNARY,
  apimessage_pb.GetTimeWarpRateRequest,
  apimessage_pb.GetTimeWarpRateResponse,
  /**
   * @param {!proto.GetTimeWarpRateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.GetTimeWarpRateResponse.deserializeBinary
);


/**
 * @param {!proto.GetTimeWarpRateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetTimeWarpRateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetTimeWarpRateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.getTimeWarpRate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/getTimeWarpRate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getTimeWarpRate,
      callback);
};


/**
 * @param {!proto.GetTimeWarpRateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetTimeWarpRateResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.getTimeWarpRate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/getTimeWarpRate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getTimeWarpRate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetFlightSceneStartTimeRequest,
 *   !proto.GetFlightSceneStartTimeResponse>}
 */
const methodDescriptor_ScratchService_getFlightSceneStartTime = new grpc.web.MethodDescriptor(
  '/ScratchService/getFlightSceneStartTime',
  grpc.web.MethodType.UNARY,
  apimessage_pb.GetFlightSceneStartTimeRequest,
  apimessage_pb.GetFlightSceneStartTimeResponse,
  /**
   * @param {!proto.GetFlightSceneStartTimeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.GetFlightSceneStartTimeResponse.deserializeBinary
);


/**
 * @param {!proto.GetFlightSceneStartTimeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetFlightSceneStartTimeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetFlightSceneStartTimeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.getFlightSceneStartTime =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/getFlightSceneStartTime',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getFlightSceneStartTime,
      callback);
};


/**
 * @param {!proto.GetFlightSceneStartTimeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetFlightSceneStartTimeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.getFlightSceneStartTime =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/getFlightSceneStartTime',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getFlightSceneStartTime);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SwitchActiveVesselRequest,
 *   !proto.SwitchActiveVesselResponse>}
 */
const methodDescriptor_ScratchService_switchActiveVessel = new grpc.web.MethodDescriptor(
  '/ScratchService/switchActiveVessel',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SwitchActiveVesselRequest,
  apimessage_pb.SwitchActiveVesselResponse,
  /**
   * @param {!proto.SwitchActiveVesselRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SwitchActiveVesselResponse.deserializeBinary
);


/**
 * @param {!proto.SwitchActiveVesselRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SwitchActiveVesselResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SwitchActiveVesselResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.switchActiveVessel =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/switchActiveVessel',
      request,
      metadata || {},
      methodDescriptor_ScratchService_switchActiveVessel,
      callback);
};


/**
 * @param {!proto.SwitchActiveVesselRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SwitchActiveVesselResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.switchActiveVessel =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/switchActiveVessel',
      request,
      metadata || {},
      methodDescriptor_ScratchService_switchActiveVessel);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SnapshotRequest,
 *   !proto.SnapshotResponse>}
 */
const methodDescriptor_ScratchService_snapshot = new grpc.web.MethodDescriptor(
  '/ScratchService/snapshot',
  grpc.web.MethodType.UNARY,
  observor_pb.SnapshotRequest,
  observor_pb.SnapshotResponse,
  /**
   * @param {!proto.SnapshotRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  observor_pb.SnapshotResponse.deserializeBinary
);


/**
 * @param {!proto.SnapshotRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SnapshotResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SnapshotResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.snapshot =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/snapshot',
      request,
      metadata || {},
      methodDescriptor_ScratchService_snapshot,
      callback);
};


/**
 * @param {!proto.SnapshotRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SnapshotResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.snapshot =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/snapshot',
      request,
      metadata || {},
      methodDescriptor_ScratchService_snapshot);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.GetVesselPartsByTypeRequest,
 *   !proto.GetVesselPartsByTypeResponse>}
 */
const methodDescriptor_ScratchService_getVesselPartsByType = new grpc.web.MethodDescriptor(
  '/ScratchService/getVesselPartsByType',
  grpc.web.MethodType.UNARY,
  apimessage_pb.GetVesselPartsByTypeRequest,
  apimessage_pb.GetVesselPartsByTypeResponse,
  /**
   * @param {!proto.GetVesselPartsByTypeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.GetVesselPartsByTypeResponse.deserializeBinary
);


/**
 * @param {!proto.GetVesselPartsByTypeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.GetVesselPartsByTypeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.GetVesselPartsByTypeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.getVesselPartsByType =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/getVesselPartsByType',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getVesselPartsByType,
      callback);
};


/**
 * @param {!proto.GetVesselPartsByTypeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.GetVesselPartsByTypeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.getVesselPartsByType =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/getVesselPartsByType',
      request,
      metadata || {},
      methodDescriptor_ScratchService_getVesselPartsByType);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SearchVesselPartsByTagRequest,
 *   !proto.SearchVesselPartsByTagResponse>}
 */
const methodDescriptor_ScratchService_searchVesselPartsByTag = new grpc.web.MethodDescriptor(
  '/ScratchService/searchVesselPartsByTag',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SearchVesselPartsByTagRequest,
  apimessage_pb.SearchVesselPartsByTagResponse,
  /**
   * @param {!proto.SearchVesselPartsByTagRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SearchVesselPartsByTagResponse.deserializeBinary
);


/**
 * @param {!proto.SearchVesselPartsByTagRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SearchVesselPartsByTagResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SearchVesselPartsByTagResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.searchVesselPartsByTag =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/searchVesselPartsByTag',
      request,
      metadata || {},
      methodDescriptor_ScratchService_searchVesselPartsByTag,
      callback);
};


/**
 * @param {!proto.SearchVesselPartsByTagRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SearchVesselPartsByTagResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.searchVesselPartsByTag =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/searchVesselPartsByTag',
      request,
      metadata || {},
      methodDescriptor_ScratchService_searchVesselPartsByTag);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.StageRequest,
 *   !proto.StageResponse>}
 */
const methodDescriptor_ScratchService_stage = new grpc.web.MethodDescriptor(
  '/ScratchService/stage',
  grpc.web.MethodType.UNARY,
  apimessage_pb.StageRequest,
  apimessage_pb.StageResponse,
  /**
   * @param {!proto.StageRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.StageResponse.deserializeBinary
);


/**
 * @param {!proto.StageRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.StageResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.StageResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.stage =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/stage',
      request,
      metadata || {},
      methodDescriptor_ScratchService_stage,
      callback);
};


/**
 * @param {!proto.StageRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.StageResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.stage =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/stage',
      request,
      metadata || {},
      methodDescriptor_ScratchService_stage);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ThrottleRequest,
 *   !proto.ThrottleResponse>}
 */
const methodDescriptor_ScratchService_throttle = new grpc.web.MethodDescriptor(
  '/ScratchService/throttle',
  grpc.web.MethodType.UNARY,
  apimessage_pb.ThrottleRequest,
  apimessage_pb.ThrottleResponse,
  /**
   * @param {!proto.ThrottleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.ThrottleResponse.deserializeBinary
);


/**
 * @param {!proto.ThrottleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ThrottleResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ThrottleResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.throttle =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/throttle',
      request,
      metadata || {},
      methodDescriptor_ScratchService_throttle,
      callback);
};


/**
 * @param {!proto.ThrottleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ThrottleResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.throttle =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/throttle',
      request,
      metadata || {},
      methodDescriptor_ScratchService_throttle);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetSASRequest,
 *   !proto.SetSASResponse>}
 */
const methodDescriptor_ScratchService_setSAS = new grpc.web.MethodDescriptor(
  '/ScratchService/setSAS',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetSASRequest,
  apimessage_pb.SetSASResponse,
  /**
   * @param {!proto.SetSASRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetSASResponse.deserializeBinary
);


/**
 * @param {!proto.SetSASRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetSASResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetSASResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setSAS =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setSAS',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setSAS,
      callback);
};


/**
 * @param {!proto.SetSASRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetSASResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setSAS =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setSAS',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setSAS);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetSASModeRequest,
 *   !proto.SetSASModeResponse>}
 */
const methodDescriptor_ScratchService_setSASMode = new grpc.web.MethodDescriptor(
  '/ScratchService/setSASMode',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetSASModeRequest,
  apimessage_pb.SetSASModeResponse,
  /**
   * @param {!proto.SetSASModeRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetSASModeResponse.deserializeBinary
);


/**
 * @param {!proto.SetSASModeRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetSASModeResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetSASModeResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setSASMode =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setSASMode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setSASMode,
      callback);
};


/**
 * @param {!proto.SetSASModeRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetSASModeResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setSASMode =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setSASMode',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setSASMode);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetRCSRequest,
 *   !proto.SetRCSResponse>}
 */
const methodDescriptor_ScratchService_setRCS = new grpc.web.MethodDescriptor(
  '/ScratchService/setRCS',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetRCSRequest,
  apimessage_pb.SetRCSResponse,
  /**
   * @param {!proto.SetRCSRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetRCSResponse.deserializeBinary
);


/**
 * @param {!proto.SetRCSRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetRCSResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetRCSResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setRCS =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setRCS',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setRCS,
      callback);
};


/**
 * @param {!proto.SetRCSRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetRCSResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setRCS =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setRCS',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setRCS);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetLightsRequest,
 *   !proto.SetLightsResponse>}
 */
const methodDescriptor_ScratchService_setLights = new grpc.web.MethodDescriptor(
  '/ScratchService/setLights',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetLightsRequest,
  apimessage_pb.SetLightsResponse,
  /**
   * @param {!proto.SetLightsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetLightsResponse.deserializeBinary
);


/**
 * @param {!proto.SetLightsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetLightsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetLightsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setLights =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setLights',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setLights,
      callback);
};


/**
 * @param {!proto.SetLightsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetLightsResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setLights =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setLights',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setLights);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetAntennasRequest,
 *   !proto.SetAntennasResponse>}
 */
const methodDescriptor_ScratchService_setAntennas = new grpc.web.MethodDescriptor(
  '/ScratchService/setAntennas',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetAntennasRequest,
  apimessage_pb.SetAntennasResponse,
  /**
   * @param {!proto.SetAntennasRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetAntennasResponse.deserializeBinary
);


/**
 * @param {!proto.SetAntennasRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetAntennasResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetAntennasResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setAntennas =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setAntennas',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setAntennas,
      callback);
};


/**
 * @param {!proto.SetAntennasRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetAntennasResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setAntennas =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setAntennas',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setAntennas);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetSolarPanelsRequest,
 *   !proto.SetSolarPanelsResponse>}
 */
const methodDescriptor_ScratchService_setSolarPanels = new grpc.web.MethodDescriptor(
  '/ScratchService/setSolarPanels',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetSolarPanelsRequest,
  apimessage_pb.SetSolarPanelsResponse,
  /**
   * @param {!proto.SetSolarPanelsRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetSolarPanelsResponse.deserializeBinary
);


/**
 * @param {!proto.SetSolarPanelsRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetSolarPanelsResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetSolarPanelsResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setSolarPanels =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setSolarPanels',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setSolarPanels,
      callback);
};


/**
 * @param {!proto.SetSolarPanelsRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetSolarPanelsResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setSolarPanels =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setSolarPanels',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setSolarPanels);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ToggleActionGroupRequest,
 *   !proto.ToggleActionGroupResponse>}
 */
const methodDescriptor_ScratchService_toggleActionGroup = new grpc.web.MethodDescriptor(
  '/ScratchService/toggleActionGroup',
  grpc.web.MethodType.UNARY,
  apimessage_pb.ToggleActionGroupRequest,
  apimessage_pb.ToggleActionGroupResponse,
  /**
   * @param {!proto.ToggleActionGroupRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.ToggleActionGroupResponse.deserializeBinary
);


/**
 * @param {!proto.ToggleActionGroupRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ToggleActionGroupResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ToggleActionGroupResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.toggleActionGroup =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/toggleActionGroup',
      request,
      metadata || {},
      methodDescriptor_ScratchService_toggleActionGroup,
      callback);
};


/**
 * @param {!proto.ToggleActionGroupRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ToggleActionGroupResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.toggleActionGroup =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/toggleActionGroup',
      request,
      metadata || {},
      methodDescriptor_ScratchService_toggleActionGroup);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetHeadingRequest,
 *   !proto.SetHeadingResponse>}
 */
const methodDescriptor_ScratchService_setHeading = new grpc.web.MethodDescriptor(
  '/ScratchService/setHeading',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetHeadingRequest,
  apimessage_pb.SetHeadingResponse,
  /**
   * @param {!proto.SetHeadingRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetHeadingResponse.deserializeBinary
);


/**
 * @param {!proto.SetHeadingRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetHeadingResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetHeadingResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setHeading =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setHeading',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setHeading,
      callback);
};


/**
 * @param {!proto.SetHeadingRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetHeadingResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setHeading =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setHeading',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setHeading);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetHeadingRollFirstRequest,
 *   !proto.SetHeadingRollFirstResponse>}
 */
const methodDescriptor_ScratchService_setHeadingRollFirst = new grpc.web.MethodDescriptor(
  '/ScratchService/setHeadingRollFirst',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetHeadingRollFirstRequest,
  apimessage_pb.SetHeadingRollFirstResponse,
  /**
   * @param {!proto.SetHeadingRollFirstRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetHeadingRollFirstResponse.deserializeBinary
);


/**
 * @param {!proto.SetHeadingRollFirstRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetHeadingRollFirstResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetHeadingRollFirstResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setHeadingRollFirst =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setHeadingRollFirst',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setHeadingRollFirst,
      callback);
};


/**
 * @param {!proto.SetHeadingRollFirstRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetHeadingRollFirstResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setHeadingRollFirst =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setHeadingRollFirst',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setHeadingRollFirst);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetOrientationRequest,
 *   !proto.SetOrientationResponse>}
 */
const methodDescriptor_ScratchService_setOrientation = new grpc.web.MethodDescriptor(
  '/ScratchService/setOrientation',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetOrientationRequest,
  apimessage_pb.SetOrientationResponse,
  /**
   * @param {!proto.SetOrientationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetOrientationResponse.deserializeBinary
);


/**
 * @param {!proto.SetOrientationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetOrientationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetOrientationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setOrientation =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setOrientation',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setOrientation,
      callback);
};


/**
 * @param {!proto.SetOrientationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetOrientationResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setOrientation =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setOrientation',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setOrientation);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.SetOrientationRollFirstRequest,
 *   !proto.SetOrientationRollFirstResponse>}
 */
const methodDescriptor_ScratchService_setOrientationRollFirst = new grpc.web.MethodDescriptor(
  '/ScratchService/setOrientationRollFirst',
  grpc.web.MethodType.UNARY,
  apimessage_pb.SetOrientationRollFirstRequest,
  apimessage_pb.SetOrientationRollFirstResponse,
  /**
   * @param {!proto.SetOrientationRollFirstRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.SetOrientationRollFirstResponse.deserializeBinary
);


/**
 * @param {!proto.SetOrientationRollFirstRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.SetOrientationRollFirstResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.SetOrientationRollFirstResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.setOrientationRollFirst =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/setOrientationRollFirst',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setOrientationRollFirst,
      callback);
};


/**
 * @param {!proto.SetOrientationRollFirstRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.SetOrientationRollFirstResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.setOrientationRollFirst =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/setOrientationRollFirst',
      request,
      metadata || {},
      methodDescriptor_ScratchService_setOrientationRollFirst);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DisengageAutoPilotRequest,
 *   !proto.DisengageAutoPilotResponse>}
 */
const methodDescriptor_ScratchService_disengageAutoPilot = new grpc.web.MethodDescriptor(
  '/ScratchService/disengageAutoPilot',
  grpc.web.MethodType.UNARY,
  apimessage_pb.DisengageAutoPilotRequest,
  apimessage_pb.DisengageAutoPilotResponse,
  /**
   * @param {!proto.DisengageAutoPilotRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.DisengageAutoPilotResponse.deserializeBinary
);


/**
 * @param {!proto.DisengageAutoPilotRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DisengageAutoPilotResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DisengageAutoPilotResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.disengageAutoPilot =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/disengageAutoPilot',
      request,
      metadata || {},
      methodDescriptor_ScratchService_disengageAutoPilot,
      callback);
};


/**
 * @param {!proto.DisengageAutoPilotRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DisengageAutoPilotResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.disengageAutoPilot =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/disengageAutoPilot',
      request,
      metadata || {},
      methodDescriptor_ScratchService_disengageAutoPilot);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.LaunchClampsReleaseRequest,
 *   !proto.LaunchClampsReleaseResponse>}
 */
const methodDescriptor_ScratchService_launchClampsRelease = new grpc.web.MethodDescriptor(
  '/ScratchService/launchClampsRelease',
  grpc.web.MethodType.UNARY,
  apimessage_pb.LaunchClampsReleaseRequest,
  apimessage_pb.LaunchClampsReleaseResponse,
  /**
   * @param {!proto.LaunchClampsReleaseRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.LaunchClampsReleaseResponse.deserializeBinary
);


/**
 * @param {!proto.LaunchClampsReleaseRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.LaunchClampsReleaseResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.LaunchClampsReleaseResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.launchClampsRelease =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/launchClampsRelease',
      request,
      metadata || {},
      methodDescriptor_ScratchService_launchClampsRelease,
      callback);
};


/**
 * @param {!proto.LaunchClampsReleaseRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.LaunchClampsReleaseResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.launchClampsRelease =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/launchClampsRelease',
      request,
      metadata || {},
      methodDescriptor_ScratchService_launchClampsRelease);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.AblatorsDecoupleRequest,
 *   !proto.AblatorsDecoupleResponse>}
 */
const methodDescriptor_ScratchService_ablatorsDecouple = new grpc.web.MethodDescriptor(
  '/ScratchService/ablatorsDecouple',
  grpc.web.MethodType.UNARY,
  apimessage_pb.AblatorsDecoupleRequest,
  apimessage_pb.AblatorsDecoupleResponse,
  /**
   * @param {!proto.AblatorsDecoupleRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.AblatorsDecoupleResponse.deserializeBinary
);


/**
 * @param {!proto.AblatorsDecoupleRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.AblatorsDecoupleResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.AblatorsDecoupleResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.ablatorsDecouple =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/ablatorsDecouple',
      request,
      metadata || {},
      methodDescriptor_ScratchService_ablatorsDecouple,
      callback);
};


/**
 * @param {!proto.AblatorsDecoupleRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.AblatorsDecoupleResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.ablatorsDecouple =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/ablatorsDecouple',
      request,
      metadata || {},
      methodDescriptor_ScratchService_ablatorsDecouple);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.DecouplersActivateRequest,
 *   !proto.DecouplersActivateResponse>}
 */
const methodDescriptor_ScratchService_decouplersActivate = new grpc.web.MethodDescriptor(
  '/ScratchService/decouplersActivate',
  grpc.web.MethodType.UNARY,
  apimessage_pb.DecouplersActivateRequest,
  apimessage_pb.DecouplersActivateResponse,
  /**
   * @param {!proto.DecouplersActivateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.DecouplersActivateResponse.deserializeBinary
);


/**
 * @param {!proto.DecouplersActivateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.DecouplersActivateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.DecouplersActivateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.decouplersActivate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/decouplersActivate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_decouplersActivate,
      callback);
};


/**
 * @param {!proto.DecouplersActivateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.DecouplersActivateResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.decouplersActivate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/decouplersActivate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_decouplersActivate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.EnginesActivateRequest,
 *   !proto.EnginesActivateResponse>}
 */
const methodDescriptor_ScratchService_enginesActivate = new grpc.web.MethodDescriptor(
  '/ScratchService/enginesActivate',
  grpc.web.MethodType.UNARY,
  apimessage_pb.EnginesActivateRequest,
  apimessage_pb.EnginesActivateResponse,
  /**
   * @param {!proto.EnginesActivateRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.EnginesActivateResponse.deserializeBinary
);


/**
 * @param {!proto.EnginesActivateRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.EnginesActivateResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.EnginesActivateResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.enginesActivate =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/enginesActivate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_enginesActivate,
      callback);
};


/**
 * @param {!proto.EnginesActivateRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.EnginesActivateResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.enginesActivate =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/enginesActivate',
      request,
      metadata || {},
      methodDescriptor_ScratchService_enginesActivate);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.EnginesShutDownRequest,
 *   !proto.EnginesShutDownResponse>}
 */
const methodDescriptor_ScratchService_enginesShutDown = new grpc.web.MethodDescriptor(
  '/ScratchService/enginesShutDown',
  grpc.web.MethodType.UNARY,
  apimessage_pb.EnginesShutDownRequest,
  apimessage_pb.EnginesShutDownResponse,
  /**
   * @param {!proto.EnginesShutDownRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.EnginesShutDownResponse.deserializeBinary
);


/**
 * @param {!proto.EnginesShutDownRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.EnginesShutDownResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.EnginesShutDownResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.enginesShutDown =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/enginesShutDown',
      request,
      metadata || {},
      methodDescriptor_ScratchService_enginesShutDown,
      callback);
};


/**
 * @param {!proto.EnginesShutDownRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.EnginesShutDownResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.enginesShutDown =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/enginesShutDown',
      request,
      metadata || {},
      methodDescriptor_ScratchService_enginesShutDown);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.FairingsJettisonRequest,
 *   !proto.FairingsJettisonResponse>}
 */
const methodDescriptor_ScratchService_fairingsJettison = new grpc.web.MethodDescriptor(
  '/ScratchService/fairingsJettison',
  grpc.web.MethodType.UNARY,
  apimessage_pb.FairingsJettisonRequest,
  apimessage_pb.FairingsJettisonResponse,
  /**
   * @param {!proto.FairingsJettisonRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.FairingsJettisonResponse.deserializeBinary
);


/**
 * @param {!proto.FairingsJettisonRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.FairingsJettisonResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.FairingsJettisonResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.fairingsJettison =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/fairingsJettison',
      request,
      metadata || {},
      methodDescriptor_ScratchService_fairingsJettison,
      callback);
};


/**
 * @param {!proto.FairingsJettisonRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.FairingsJettisonResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.fairingsJettison =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/fairingsJettison',
      request,
      metadata || {},
      methodDescriptor_ScratchService_fairingsJettison);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.ParachutesDeployRequest,
 *   !proto.ParachutesDeployResponse>}
 */
const methodDescriptor_ScratchService_parachutesDeploy = new grpc.web.MethodDescriptor(
  '/ScratchService/parachutesDeploy',
  grpc.web.MethodType.UNARY,
  apimessage_pb.ParachutesDeployRequest,
  apimessage_pb.ParachutesDeployResponse,
  /**
   * @param {!proto.ParachutesDeployRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.ParachutesDeployResponse.deserializeBinary
);


/**
 * @param {!proto.ParachutesDeployRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.ParachutesDeployResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.ParachutesDeployResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.parachutesDeploy =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/parachutesDeploy',
      request,
      metadata || {},
      methodDescriptor_ScratchService_parachutesDeploy,
      callback);
};


/**
 * @param {!proto.ParachutesDeployRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.ParachutesDeployResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.parachutesDeploy =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/parachutesDeploy',
      request,
      metadata || {},
      methodDescriptor_ScratchService_parachutesDeploy);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.RCSesEnabledRequest,
 *   !proto.RCSesEnabledResponse>}
 */
const methodDescriptor_ScratchService_RCSesEnabled = new grpc.web.MethodDescriptor(
  '/ScratchService/RCSesEnabled',
  grpc.web.MethodType.UNARY,
  apimessage_pb.RCSesEnabledRequest,
  apimessage_pb.RCSesEnabledResponse,
  /**
   * @param {!proto.RCSesEnabledRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  apimessage_pb.RCSesEnabledResponse.deserializeBinary
);


/**
 * @param {!proto.RCSesEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.RCSesEnabledResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.RCSesEnabledResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.ScratchServiceClient.prototype.rCSesEnabled =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/ScratchService/RCSesEnabled',
      request,
      metadata || {},
      methodDescriptor_ScratchService_RCSesEnabled,
      callback);
};


/**
 * @param {!proto.RCSesEnabledRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.RCSesEnabledResponse>}
 *     Promise that resolves to the response
 */
proto.ScratchServicePromiseClient.prototype.rCSesEnabled =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/ScratchService/RCSesEnabled',
      request,
      metadata || {},
      methodDescriptor_ScratchService_RCSesEnabled);
};


module.exports = proto;

